spring:
  datasource:
    druid:
      sid:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/manydatasource1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: root
        password: mysqladmin
        initialSize: 1
        maxActive: 20
        minIdle: 1
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filters: stat,wall,slf4j
      lee:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/manydatasource2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: root
        password: mysqladmin
        initialSize: 1
        maxActive: 20
        minIdle: 1
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filters: stat,wall,slf4j
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false